### ISSUE TITLE
Set PATH for publish on s3 - SBT (remove scala & sbt version)

### ISSUE THREAD

**Issue by AarganC** [tpunder/fm-sbt-s3-resolver#49]
Hi,

I have a project where I need to publish my FatJar on AWS s3. I have difficulties to set PATH on s3.
##Log of publish
```
[cloudera@quickstart framework]$ sbt publish
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /home/cloudera/IdeaProjects/framework/project
[info] Set current project to Framework (in build file:/home/cloudera/IdeaProjects/framework/)
[info] Installing the s3:// URLStreamHandler via java.net.URL.setURLStreamHandlerFactory
[info] Creating a new Ivy URLHandlerDispatcher to handle s3:// URLs
[info] Packaging /home/cloudera/IdeaProjects/framework/target/sbt-0.13/framework-1.0.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] :: delivering :: com.bucket#framework;1.0.0-SNAPSHOT :: 1.0.0-SNAPSHOT :: integration :: Thu Jun 28 09:09:57 PDT 2018
[info]  delivering ivy file to /home/cloudera/IdeaProjects/framework/target/sbt-0.13/ivy-1.0.0-SNAPSHOT.xml
[info] Main Scala API documentation to /home/cloudera/IdeaProjects/framework/target/sbt-0.13/api...
[info] Wrote /home/cloudera/IdeaProjects/framework/target/sbt-0.13/framework-1.0.0-SNAPSHOT.pom
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Packaging /home/cloudera/IdeaProjects/framework/target/sbt-0.13/framework-1.0.0-SNAPSHOT.jar ...
[info] Done packaging.
model contains 56 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /home/cloudera/IdeaProjects/framework/target/sbt-0.13/framework-1.0.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info] S3URLHandler - Looking up AWS Credentials for bucket: bucket ...
[info] S3URLHandler - Using AWS Access Key Id: ******************* for bucket: bucket
[info] S3URLHandler - Created S3 Client for bucket: bucket and region: eu-west-1
[info]  published framework to s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/framework_2.11_0.13/1.0.0-SNAPSHOT/framework-1.0.0-SNAPSHOT.pom
[info]  published framework to s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/framework_2.11_0.13/1.0.0-SNAPSHOT/framework-1.0.0-SNAPSHOT.jar
[info]  published framework to s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/framework_2.11_0.13/1.0.0-SNAPSHOT/framework-1.0.0-SNAPSHOT-sources.jar
[info]  published framework to s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/framework_2.11_0.13/1.0.0-SNAPSHOT/framework-1.0.0-SNAPSHOT-javadoc.jar
[success] Total time: 16 s, completed Jun 28, 2018 9:10:13 AM
```
The problem in this log is on a path : *s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/framework_2.11_0.13/1.0.0-SNAPSHOT/framework-1.0.0-SNAPSHOT.*

I need to take the path in this format : *s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/framework/1.0.0-SNAPSHOT/framework-1.0.0-SNAPSHOT.*

Because when I try to resolve my dependencies from this FatJar I have an error message when I use this resolver :
##~/build.sbt
```
crossPaths := false
libraryDependencies ++= Seq(
  "com.bucket" %% "framework_2.11_0.13" % "1.0.0-SNAPSHOT" % "provided"
)
```
##Log of resolver
```
Error:Error while importing SBT project:<br/>...<br/><pre>[warn] ==== local: tried
[warn]   /home/cloudera/.ivy2/local/com.bucket/framework_2.11_0.13_2.11/1.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/bucket/framework_2.11_0.13_2.11/1.0.0-SNAPSHOT/framework_2.11_0.13_2.11-1.0.0-SNAPSHOT.pom
[warn] ==== framework-1.0.0-SNAPSHOT.jar: tried
[warn]   s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/framework_2.11_0.13_2.11/1.0.0-SNAPSHOT/framework_2.11_0.13_2.11-1.0.0-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.bucket#framework_2.11_0.13_2.11;1.0.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]      com.bicket:framework_2.11_0.13_2.11:1.0.0-SNAPSHOT (/home/cloudera/IdeaProjects/job/build.sbt#L32-39)
[warn]        +- ohnosequences:frameworkjobs:0.0.8 (scalaVersion=2.11, sbtVersion=0.13)
[trace] Stack trace suppressed: run 'last *:ssExtractProject' for the full output.
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:ssExtractProject) sbt.ResolveException: unresolved dependency: com.bucket#framework_2.11_0.13_2.11;1.0.0-SNAPSHOT: not found
[error] (*:update) sbt.ResolveException: unresolved dependency: com.bucket#framework_2.11_0.13_2.11;1.0.0-SNAPSHOT: not found
[error] Total time: 6 s, completed Jun 28, 2018 9:42:14 AM</pre><br/>See complete log in <a href="file:/home/cloudera/.IdeaIC2017.1/system/log/sbt.last.log">file:/home/cloudera/.IdeaIC2017.1/system/log/sbt.last.log</a>
```
But when I edit the path on my bucket s3 same that : *s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/framework/1.0.0-SNAPSHOT/framework-1.0.0-SNAPSHOT.* 
and my resolver same that :
```
libraryDependencies ++= Seq(
  "com.bucket" % "framework" % "1.0.0-SNAPSHOT" % "provided"
) 
```
the resolver work corretly.

I'm search one of two solutions :
- Resolve the dependencie with the scala & sbt version.
- Publish the FatJar without version of scala & sbt on the path.

Thanks for your help !

**Comment by AarganC** [comment]
Okay, I beginning to move forward. 
When I resolve the dependencies, just the `.pom` need path without scala and SBT version.

### Log with this pas on s3 : s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/bucket/sparkframework_2.11_0.13/1.0.0-SNAPSHOT/sparkframework-1.0.0-SNAPSHOT* ###
`
Error:Error while importing SBT project:<br/>...<br/><pre>[warn] ==== local: tried
[warn]   /home/cloudera/.ivy2/local/com.bucket/sparkframework/1.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/bucket/sparkframework/1.0.0-SNAPSHOT/sparkframework-1.0.0-SNAPSHOT.pom
[warn] ==== s3: tried
[warn]   s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/bucket/sparkframework/1.0.0-SNAPSHOT/sparkframework-1.0.0-SNAPSHOT.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.bucket#sparkframework;1.0.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.bucket:sparkframework:1.0.0-SNAPSHOT (/home/cloudera/IdeaProjects/build.sbt#L32-39)
[warn] 		  +- com.bucket.spark.apx:sparkjobsapx:0.0.8 (scalaVersion=2.11, sbtVersion=0.13)
[trace] Stack trace suppressed: run 'last *:ssExtractProject' for the full output.
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:ssExtractProject) sbt.ResolveException: unresolved dependency: com.bucket#sparkframework;1.0.0-SNAPSHOT: not found
[error] (*:update) sbt.ResolveException: unresolved dependency: com.bucket#sparkframework;1.0.0-SNAPSHOT: not found
[error] Total time: 8 s, completed Jul 3, 2018 5:23:13 AM</pre><br/>See complete log in <a href="file:/home/cloudera/.IdeaIC2017.1/system/log/sbt.last.log">file:/home/cloudera/.IdeaIC2017.1/system/log/sbt.last.log</a>
`

When I delete the version on my PATH on s3 :
### Log with this pas on s3 : s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/bucket/sparkframework/1.0.0-SNAPSHOT/sparkframework-1.0.0-SNAPSHOT* 
`
Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving joda-time#joda-time;2.9.9 ...
[info] Resolving com.databricks#spark-redshift_2.11;3.0.0-preview1 ...
[info] Resolving com.eclipsesource.minimal-json#minimal-json;0.9.4 ...
[info] Resolving com.databricks#spark-avro_2.11;3.2.0 ...
[info] Resolving org.apache.avro#avro;1.7.6 ...
[info] Resolving org.xerial.snappy#snappy-java;1.0.5 ...
[warn] 	[NOT FOUND  ] com.bucket#sparkframework;1.0.0-SNAPSHOT!sparkframework.jar (1ms)
[warn] ==== s3: tried
[warn]   s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/bucket/sparkframework_2.11_0.13/1.0.0-SNAPSHOT/sparkframework-1.0.0-SNAPSHOT.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.bucket#sparkframework;1.0.0-SNAPSHOT!sparkframework.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run 'last *:ssExtractProject' for the full output.
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:ssExtractProject) sbt.ResolveException: download failed: com.bucket#sparkframework;1.0.0-SNAPSHOT!sparkframework.jar
[error] (*:update) sbt.ResolveException: download failed: com.bucket#sparkframework;1.0.0-SNAPSHOT!sparkframework.jar
[error] Total time: 12 s, completed Jul 3, 2018 6:42:51 AM</pre><br/>See complete log in <a href="file:/home/cloudera/.IdeaIC2017.1/system/log/sbt.last.log">file:/home/cloudera/.IdeaIC2017.1/system/log/sbt.last.log</a>
`

Have you a tip or solution for getting around this problem ?
Because actually I need to develop a Jenkins Job where after a publish on `s3`, the `.pom` is moving from `s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/bucket/sparkframework_2.11_0.13/1.0.0-SNAPSHOT/` to `s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/com/bucket/sparkframework/1.0.0-SNAPSHOT/`.
Thanks.

**Comment by tpunder** [comment]
The  `sbt-0.13` part seems to imply you are creating an SBT plugin (which would include the SBT version as part of the published path):
```
/home/cloudera/IdeaProjects/framework/target/sbt-0.13/framework-1.0.0-SNAPSHOT.jar
```

If that is not what you are trying to do then this would be an SBT configuration issue.

My plugin doesn't do anything special with the path.  That's all driven by SBT (or perhaps Ivy).  All this plugin does is provide a way for SBT to put or get a file for a given path to or from S3.  It doesn't come up with what the path should be.

**Comment by AarganC** [comment]
Okay, I understand that plugin build the path with the information provided in a sbt or other.
I'm just searching to understand how build the path correctly without action in addition.

But I don't understand why the path is different for recover the `.jar` and the `.pom`. (I `publish` and `resolve` with your plugin)

This is my ~/build.sbt
```
import ReleaseTransformations._
import com.amazonaws.auth.{AWSStaticCredentialsProvider, BasicAWSCredentials}

name := "SparkJobs"

organization := "com.bucket.spark"

scalaVersion := "2.11.8"

parallelExecution in Test := false

sbtPlugin := true

val sparkVersion = "2.1.0"

s3CredentialsProvider := { (bucket: String) =>
  new AWSStaticCredentialsProvider(new BasicAWSCredentials("******************", "******************************"))
}

resolvers +=  "s3" at "s3://bucket.s3-eu-west-1.amazonaws.com/artifacts/rc/"

libraryDependencies ++= Seq(
  "com.bucket" % "bucketsparkframework" % "1.0.0-SNAPSHOT" % "provided",
  "org.apache.spark" %% "spark-core" % sparkVersion % "provided" exclude("org.json4s","json4s-ast_2.11") exclude("org.json4s","json4s-core_2.11"),
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided" exclude("org.json4s","json4s-ast_2.11") exclude("org.json4s","json4s-core_2.11"),
  "com.holdenkarau" %% "spark-testing-base" % "2.1.0_0.6.0" % "test",
  "org.scalatest" %% "scalatest" % "3.0.1" % "test"
)

updateOptions := updateOptions.value.withCachedResolution(true)

assemblyMergeStrategy in assembly := {
  case PathList("javax", "servlet", xs@_*) => MergeStrategy.first
  case PathList("org", xs@_*) => MergeStrategy.first
  case PathList(ps@_*) if ps.last endsWith ".html" => MergeStrategy.first
  case "application.conf" => MergeStrategy.concat
  case "unwanted.txt" => MergeStrategy.discard
  case "META-INF/io.netty.versions.properties" => MergeStrategy.first
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}

releaseProcess := Seq[ReleaseStep](
  inquireVersions,
  runClean,
  runTest,
  setReleaseVersion,
  releaseStepCommand("assembly"),
  commitReleaseVersion,
  setNextVersion,
  commitNextVersion,
  pushChanges
)

```
assembly.sbt
`addSbtPlugin("com.eed3si9n" % "sbt-assembly" %`

build.properties
`sbt.version=0.13.15`

plugins.sbt 
```
logLevel := Level.Warn
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.6")

addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.14.0")
```

**Comment by tpunder** [comment]
I'm missing the complete picture here because it looks like you have multiple projects but you've only posted one of the projects and it's name does not match any of the logging output from your earlier posts so I'm not really sure how all of these are related.

In the build.sbt you posted above if you run `sbt publish` you should get the `2.11_0.13` in the path because it's an `sbtPlugin := true`.  If you later try to resolve that you should use `addSbtPlugin(...)` so that SBT knows how to construct the path to it.

Is it the resolution of the `"com.bucket" % "bucketsparkframework" % "1.0.0-SNAPSHOT" % "provided"` dependency that you are having issues with?

**Comment by tpunder** [comment]
Closing old issue. Re-open if needed.
