### ISSUE TITLE
Missing WebIdentityTokenCredentialsProvider with AWS SDK 1.11.507

### ISSUE THREAD

**Issue by msangoi** [tpunder/fm-sbt-s3-resolver#61]
The `WebIdentityTokenCredentialsProvider` provider is required when running in EKS with 'IAM roles for service accounts'.
This provider is not part of the `DefaultAWSCredentialsProviderChain` in version `1.11.507` of the SDK.

Bumping to version `1.11.718` fixed the problem.
I'm not sure in which version the changed was introduced. From the comments in [this issue](https://github.com/aws/aws-sdk-java/issues/2136), it seems to be around `1.11.704`. 

Thanks.

**Comment by tpunder** [comment]
@msangoi I just published version `0.20.0` which upgrades to the latest AWS SDK for Java (`1.12.99`). Hopefully this picks up the updated `DefaultAWSCredentialsProviderChain`.

**Comment by msangoi** [comment]
Thanks @tpunder. I confirm it is ok with version `0.20.0` 👍
