### ISSUE TITLE
SBT 1.4 support

### ISSUE THREAD

**Issue by diraol** [tpunder/fm-sbt-s3-resolver#76]
Hello 👋🏽,

does this plugging works in `sbt 1.4.9`?
I couldn't find any official statement about it, but I'd also like to know if someone is running sbt 1.4 with this plugin successfully.

Thanks!

**Comment by tpunder** [comment]
Hi @diraol,

Yeah I see how that could be confusing from the README.md page. But YES it works fine for 1.4, 1.5 and 1.6 also. I'm currently on 1.6.2 for some of my projects without any problems.

**Comment by tpunder** [comment]
@diraol I attempted to clarify this on the README.md page.

**Comment by diraol** [comment]
Perfect, thanks for the clarification! :)
